print('\033[0;32;1m=\033[m'*50)
print('\033[0;32;1mDescubra o tipo primitivo e mais informações: \033[m')
print('\033[0;32;1m=\033[m'*50)
analise = input('Digite algo para análise: ').strip()
print('O tipo primitivo desse valor é: ', type(analise))
print('Só tem espaços? ', analise.isspace())
print('Só tem letras? ', analise.isalpha())
print('Só tem números? ', analise.isnumeric())
print('É alfanumérico? ', analise.isalnum())
print('Só tem letras maiúsculas? ', analise.isupper())
print('Só tem letras minúsculas? ', analise.islower())
print('Está capitalizada?  ', analise.istitle())
print('\033[0;31;1m=\033[m'*50)
print('\033[0;31;1mFim da análise...\033[m')
print('\033[0;31;1m=\033[m'*50)

